### ISSUE TITLE
Segmentation fault when update checking is enabled (AppImage)

### ISSUE THREAD

**Issue by cottnn** [muttleyxd/arma3-unix-launcher#212] opened 2022-03-12 16:08 UTC
When I have update checking enabled, I'm getting a segmentation fault at startup (the main window pops up for a moment and closes; `zsh: segmentation fault  arma3-unix-launcher` in the terminal). I'm using the AppImage version.
This happened both when I enabled update checking via the GUI dialog and when I enabled it in the config file directly.

```
$ uname -a
Linux main 5.15.24_1 #1 SMP Wed Feb 16 16:03:52 UTC 2022 x86_64 GNU/Linux
```
libc: `glibc-2.32_2`

**Comment by muttleyxd** [comment] 2022-03-12 16:10
Which distribution are you using? This would be easiest for me to reproduce it (since I can run launcher in a VM or Docker)

Also please try running launcher with `--verbose` flag and post logs here

**Comment by cottnn** [comment] 2022-03-12 17:24
I'm using [Void Linux](https://voidlinux.org)
```
[2022-03-12 17:21:00.398] [info] Started Arma 3 Unix Launcher, config file path: "/home/void/.config/a3unixlauncher/launch
[2022-03-12 17:21:00.398] [debug] arma path: '/home/void/.local/share/Steam/steamapps/common/Arma 3', workshop path: ''
[S_API] SteamAPI_Init(): Loaded '/home/void/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561234567890123 [API loaded no]
[2022-03-12 17:21:00.580] [trace] trying to get workshop mods
zsh: segmentation fault  arma3-unix-launcher --verbose
```

**Comment by BRINGit34** [comment] 2022-03-12 19:17
I am getting the exact same issue here on fedora 35 using the newest release of the dayz launcher

**Comment by muttleyxd** [comment] 2022-03-15 11:15
This should be fixed by newest release. Feel free to reopen or comment if issue persists.

**Closed by muttleyxd** 2022-03-15 11:15 UTC
